### PR TITLE
Fix Flare-Capa install

### PR DESCRIPTION
**Pull request by ClaudioWayne**
Hallo Sir,
Flare-Capa install did not work for me.

Error 1:
pyhtonNotFouond

What worked for me: 
-> python3 setup.py install

Error 2
Repeat

What worked for me: 
I guess just duplicated code  -> delete

### CODE REVIEW

**Comment by doomedraven** [comment]
ah good catch, my bad c&p as always ahahah, thank you

**Comment by doomedraven** [comment]
fixed second part with this

```
# pip3 install flare-capa fails for me
    cd /tmp || return
    if [ ! -d /tmp/capa ]; then
        git clone --recurse-submodules https://github.com/fireeye/capa.git
    fi
    cd capa || return
    git pull
    git submodule update --init rules
    python3 setup.py install
```

**Comment by doomedraven** [comment]
FYI ` python3 setup.py install` i don't suggest you yo use that, as it will end in cleanup problem later on updates, use `pip3 install .` that will be managed by pip just fine, i just spot that i have to fix my code now lol

**Comment by ClaudioWayne** [comment]
thx for info

**Comment by doomedraven** [comment]
always welcome, thanks for fix

**Pull request merged**
