### PR TITLE
remove unexisting ubuntu packages ubuntu-20.04

### PR DESCRIPTION
**Pull request by t14g0p**
remove unexisting ubuntu packages breaking virtmanager installation

### CODE REVIEW

**Comment by doomedraven** [comment]
hello, thank you, but the uniq lib which i can't fin in 20.04 is python3-minimal as py3 is default python on it, the rest is there just fine

```
ovmf/focal,focal,now 0~20191122.bd85bf54-2ubuntu3 all
python3-ntlm-auth/focal,focal 1.1.0-1 all
libxen-4.9/now 4.9.2-0ubuntu1 amd64
ocaml-findlib/focal 1.8.1-1build3
libvpx5/now 1.7.0-3ubuntu0.18.04.1 amd64
libpython3-stdlib/focal,now 3.8.2-0ubuntu2 amd64
libbrlapi0.6/now 5.5-4ubuntu2.0.1 amd64
```

**Comment by t14g0p** [comment]
Thank you for these tools, they are very helpful!
Regarding this issues, it is strange that you can find these libs. I tried it multiple times and they dont exist on a clean, updated ubuntu (20.04 or 18.04) the packages I removed don't exist, which result in the apt command failing, which results in virtmanager not working.

I'm running on a clean updated VM: 

sudo -H ./kvm-qemu.sh all

**Comment by doomedraven** [comment]
glad that is useful, hm interesting, im gonna build new ubuntu 20.04 and test it again

**Comment by doomedraven** [comment]
ya i can see them on my clean vm,  and on full update vm to latest updates, what im gonna do is just move them to separated line so they shouldn't affect, and if they are they will be insatlled and if not found ignored

**Comment by doomedraven** [comment]
done, thanks again

**Pull request closed without merging**
