### PR TITLE
jemalloc dep, qemu build fix

### PR DESCRIPTION
**Pull request by ClaudioWayne**
from fresh ubuntu:
```
./kvm-qemu.sh: line 774: curl: command not found
./kvm-qemu.sh: line 775: jq: command not found
./kvm-qemu.sh: line 776: jq: command not found
./kvm-qemu.sh: line 784: ./autogen.sh: No such file or directory
./kvm-qemu.sh: line 785: make: command not found
./kvm-qemu.sh: line 786: checkinstall: command not found
```

-> aptitude install -f checkinstall curl build-essential jq autoconf -y

Not sure if its necessary to install jemalloc before qemu_func or in qemu_func . Maybe put install_jemalloc in all comannd? 

-----

```
E: Unsupported file ./qemu-5.2.0/qemu-5.2.0-1_amd64.deb given on commandline
[+] Patched, compiled and installed
[?] tss Group and User exist, skip
```

Not sure about that, but we are already in /tmp/qemu-5.2.0
What worked for me:
-> `apt -y -o Dpkg::Options::="--force-overwrite" install ./qemu-$qemu_version\_$qemu_version-1_amd64.deb`

-----

added autofill username

### CODE REVIEW

**Comment by doomedraven** [comment]
thanks, the username filling placed in wrong place, if you want to build all it will contain bad value

**Comment by ClaudioWayne** [comment]
oh okay, you are right, maybe better on top of script or in function where username is added?

**Comment by doomedraven** [comment]
yes user just should place the username in there, it could be a trick added to check if first arg lets say `qemu` so it would then check if second arg is set and set it as username, but not direclty when first one is `all`

**Comment by doomedraven** [comment]
about jemalloc is before qemu to allow compile qemu with jemalloc support
about dv  install hm i will need to check as i had verified/fixed in a bit ago, anyway a lot of shellcheck fixes coming, so if you remove the username i will merge

**Pull request merged**
